### ISSUE TITLE
4.1 log format changed 

### ISSUE THREAD

**Issue by EosBandi** [ArduPilot/plotjuggler-apbin-plugins#2]
Log messages not contains Instance field and store data from multiple instances in the same message id. 
For example XKF1 now contains log from all EKF lanes...

**Comment by khancyr** [comment]
Hello,
I will look at that but normally the parsing is done with the information from the message type itself, so if the definition is done correctly the parsing should be correct too.

**Comment by Georacer** [comment]
It's not an issue on the parser itself. But recently the following messages have added an "instance" field that refers to different instances/core relaying the same fields but referring to different variables. But since they all write to the same topic the automated decoder dumps them all in the same topic, making it hard to visualize and use.

Here's what I did for the issue in Ardupilog: https://github.com/Georacer/ardupilog/commit/46e1584ef0a54b73486bffe684795d91e7767533

**Comment by EosBandi** [comment]
Indeed, but even ardupilog is outdated at the moment, since now IMU, MAG, GPS and other sensor messages are having instance field as well. (Make it worst, the field name is not C but with sensors)

**Comment by EosBandi** [comment]
From UAVLogViewer, it seems that a '#' unit type indicates instance, so you can automate detecting "instanced" messages....
https://github.com/ArduPilot/UAVLogViewer/blob/d09775cfc392b285d1244e2c8e16f935c194f2f6/src/tools/parsers/dataflashParser.js#L142
But have to process FMTU messages as well.

**Comment by Georacer** [comment]
> Indeed, but even ardupilog is outdated at the moment, since now IMU, MAG, GPS and other sensor messages are having instance field as well. (Make it worst, the field name is not C but with sensors)

There was a feature branch that addressed this, I just merged it to master.

**Comment by Georacer** [comment]
> From UAVLogViewer, it seems that a '#' unit type indicates instance, so you can automate detecting "instanced" messages....
> https://github.com/ArduPilot/UAVLogViewer/blob/d09775cfc392b285d1244e2c8e16f935c194f2f6/src/tools/parsers/dataflashParser.js#L142
> But have to process FMTU messages as well.

I didn't know this. Good info, thanks!
